import {useEffect, useState} from "react";

export const useProductos = () => {

    const [productos, setProductos] = useState([]);

    useEffect(() => {

        setTimeout(() => {
            setProductos([
                    {
                        "id": "1",
                        "categoria": "Ropa",
                        "nombre": "Vestido floral",
                        "empresa": "Moda Primavera",
                        "descripcion_corta": "Vestido floral para ocasiones especiales",
                        "descripcion_larga": "Vestido elegante con estampado floral perfecto para eventos y ocasiones especiales. Confeccionado con materiales de alta calidad que garantizan comodidad y estilo. Diseño exclusivo que resalta tu elegancia. Disponible en talla S y en un hermoso estampado floral. ¡Destaca en tus eventos con este magnífico vestido!",
                        "precio": 59.99,
                        "imagen": "https://static.oysho.net/6/photos2/2023/I/3/1/p/0752/320/647/0752320647_4_2_0.jpg?t=1678351343216",
                        "talla": "S",
                        "color": "Floral"
                    },
                    {
                        "id": "2",
                        "categoria": "Zapatos",
                        "nombre": "Botas de invierno",
                        "empresa": "Calzado Cálido",
                        "descripcion_corta": "Botas resistentes para el invierno",
                        "descripcion_larga": "Botas de invierno resistentes al agua con forro térmico. Ideales para climas fríos. Diseño moderno que combina estilo y funcionalidad. Suela antideslizante que proporciona seguridad en superficies resbaladizas. Disponibles en talla M y en color negro clásico. ¡Mantén tus pies cálidos y a la moda durante la temporada de invierno!",
                        "precio": 79.99,
                        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPFGzlUyLEBpXFGn96EO4PgTTWMAx6B6exTw&usqp=CAU",
                        "talla": "M",
                        "color": "Negro"
                    },
                    {
                        "id": "3",
                        "categoria": "Accesorios",
                        "nombre": "Gafas de sol",
                        "empresa": "Estilo UV",
                        "descripcion_corta": "Gafas de sol con protección UV",
                        "descripcion_larga": "Gafas de sol con montura de metal y protección UV. Estilo moderno y duradero. Lentes polarizadas que ofrecen una visión nítida y sin deslumbramientos. Diseño plateado que añade un toque elegante a tu look. Fabricadas con materiales de alta calidad para garantizar durabilidad y resistencia. ¡Protege tus ojos con estilo!",
                        "precio": 39.99,
                        "imagen": "https://sunpersunglasses.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/s/u/su40005.16_2_.jpg",
                        "color": "Plateado"
                    },
                    {
                        "id": "4",
                        "categoria": "Ropa",
                        "nombre": "Pantalones vaqueros",
                        "empresa": "Estilo Denim",
                        "descripcion_corta": "Pantalones vaqueros clásicos",
                        "descripcion_larga": "Pantalones vaqueros cómodos y duraderos. Estilo clásico para cualquier ocasión. Confeccionados con denim de alta calidad que garantiza resistencia y comodidad. Disponibles en talla L y en un atractivo tono azul. Combina estos pantalones con cualquier camisa o top para un look casual y elegante. ¡Un básico imprescindible en tu guardarropa!",
                        "precio": 49.99,
                        "imagen": "https://media.vogue.es/photos/6353b4088b2ff6e8ce173b85/3:4/w_748%2Cc_limit/Captura%2520de%2520pantalla%25202022-10-22%2520a%2520las%252011.12.09.png",
                        "talla": "L",
                        "color": "Azul"
                    },
                    {
                        "id": "5",
                        "categoria": "Ropa",
                        "nombre": "Camisa a rayas",
                        "empresa": "Estilo Casual",
                        "descripcion_corta": "Camisa de manga larga a rayas",
                        "descripcion_larga": "Camisa de manga larga con patrón a rayas. Confeccionada con algodón suave y transpirable. Perfecta para un look casual y cómodo. Disponible en talla XL y en diferentes combinaciones de colores. ¡Añade un toque moderno a tu colección de camisas!",
                        "precio": 29.99,
                        "imagen": "https://media.revistagq.com/photos/60ace2fa5afdf213ad9f0096/master/w_1600%2Cc_limit/camisa%2520rayas%2520zara.jpg",
                        "talla": "XL",
                        "color": "Rayas"
                    },
                    {
                        "id": "6",
                        "categoria": "Zapatos",
                        "nombre": "Zapatillas deportivas",
                        "empresa": "Deporte Activo",
                        "descripcion_corta": "Zapatillas cómodas para actividades deportivas",
                        "descripcion_larga": "Zapatillas deportivas ideales para actividades físicas. Con tecnología de amortiguación para mayor comodidad. Disponibles en talla 9 y en varios colores vibrantes. ¡Potencia tu rendimiento deportivo con estas zapatillas!",
                        "precio": 69.99,
                        "imagen": "https://statics.venca.com/web/img/products/066444_304227_PV_DF_FR_20230125091035_1_l.jpg",
                        "talla": "9",
                        "color": "Rojo"
                    },
                    {
                        "id": "7",
                        "categoria": "Accesorios",
                        "nombre": "Bolso de cuero",
                        "empresa": "Estilo Elegante",
                        "descripcion_corta": "Bolso de cuero genuino",
                        "descripcion_larga": "Bolso elegante confeccionado en cuero genuino. Diseño espacioso y versátil para llevar tus pertenencias con estilo. Disponible en varios colores clásicos. ¡Completa tu look con este bolso de alta calidad!",
                        "precio": 89.99,
                        "imagen": "https://belcorpecuador.vtexassets.com/arquivos/ids/288012-800-800?v=638366994669900000&width=800&height=800&aspect=true",
                        "color": "Negro"
                    },
                    {
                        "id": "8",
                        "categoria": "Ropa",
                        "nombre": "Abrigo de lana",
                        "empresa": "Moda Invernal",
                        "descripcion_corta": "Abrigo de lana para climas fríos",
                        "descripcion_larga": "Abrigo de lana con forro térmico, ideal para climas fríos. Diseño elegante y cálido. Disponible en talla M y en varios colores. ¡Mantente abrigado y a la moda durante el invierno con este sofisticado abrigo!",
                        "precio": 119.99,
                        "imagen": "https://static.goldengoose.com/image/upload/w_auto,c_scale,f_auto,q_auto/v1683204724/Style/ECOMM/GWP01510.P001167-35856",
                        "talla": "M",
                        "color": "Gris"
                    },
                    {
                        "id": "9",
                        "categoria": "Accesorios",
                        "nombre": "Reloj de pulsera",
                        "empresa": "Estilo Clásico",
                        "descripcion_corta": "Reloj de pulsera elegante",
                        "descripcion_larga": "Reloj de pulsera con diseño clásico y elegante. Correa de cuero genuino y esfera analógica. Resistente al agua y duradero. Disponible en varios colores. ¡Completa tu look con este accesorio atemporal!",
                        "precio": 59.99,
                        "imagen": "https://http2.mlstatic.com/D_NQ_NP_923525-MLU71400411859_082023-O.webp",
                        "color": "Marrón"
                    },
                    {
                        "id": "10",
                        "categoria": "Ropa",
                        "nombre": "Suéter tejido",
                        "empresa": "Estilo Cálido",
                        "descripcion_corta": "Suéter tejido para días frescos",
                        "descripcion_larga": "Suéter tejido confeccionado en material suave y cálido. Ideal para días frescos y noches frías. Disponible en talla L y en varios colores. ¡Añade un toque acogedor a tu guardarropa con este suéter elegante!",
                        "precio": 45.99,
                        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0jo0SOMW3tsHspyWrdIE6p_zUEYO2pnQEaQ&usqp=CAU",
                        "talla": "L",
                        "color": "Verde"
                    },
                    {
                        "id": "11",
                        "categoria": "Accesorios",
                        "nombre": "Collar de perlas",
                        "empresa": "Joyas Elegantes",
                        "descripcion_corta": "Collar clásico de perlas",
                        "descripcion_larga": "Collar de perlas con diseño clásico y atemporal. Perfecto para ocasiones especiales y eventos formales. Hecho con perlas de alta calidad. ¡Realza tu elegancia con este accesorio encantador!",
                        "precio": 89.99,
                        "imagen": "https://www.joyeriavalencia.com.ec/wp-content/uploads/2020/06/1678-COLLAR-DE-PERLAS-CON-BROCHE-DE-ORO-BLANCO.jpg",
                        "color": "Blanco"
                    },
                    {
                        "id": "12",
                        "categoria": "Ropa",
                        "nombre": "Chaqueta de cuero",
                        "empresa": "Estilo Rebelde",
                        "descripcion_corta": "Chaqueta de cuero con cremallera",
                        "descripcion_larga": "Chaqueta de cuero con diseño moderno y cremallera frontal. Ideal para un look rebelde y a la moda. Disponible en talla M y en varios colores. ¡Añade un toque audaz a tu vestuario con esta chaqueta!",
                        "precio": 109.99,
                        "imagen": "https://i.ebayimg.com/thumbs/images/g/~qMAAOSwHgZk9IYZ/s-l640.jpg",
                        "talla": "M",
                        "color": "Negro"
                    },
                    {
                        "id": "13",
                        "categoria": "Zapatos",
                        "nombre": "Sandalias de verano",
                        "empresa": "Calzado Fresco",
                        "descripcion_corta": "Sandalias cómodas para el verano",
                        "descripcion_larga": "Sandalias ligeras y transpirables ideales para el verano. Con diseño ergonómico para mayor comodidad. Disponibles en talla 8 y en varios colores. ¡Pasea con estilo y frescura durante los días soleados!",
                        "precio": 49.99,
                        "imagen": "https://m.media-amazon.com/images/I/81cnNTk-1eS._AC_SY300_QL65_.jpg",
                        "talla": "8",
                        "color": "Azul"
                    },
                    {
                        "id": "14",
                        "categoria": "Ropa",
                        "nombre": "Vestido de cóctel",
                        "empresa": "Moda Elegante",
                        "descripcion_corta": "Vestido de cóctel para ocasiones especiales",
                        "descripcion_larga": "Vestido de cóctel con diseño elegante y favorecedor. Perfecto para eventos formales y fiestas. Disponible en talla S y en varios colores. ¡Deslumbra en tus eventos sociales con este encantador vestido!",
                        "precio": 79.99,
                        "imagen": "https://e00-elmundo.uecdn.es/assets/multimedia/imagenes/2023/05/08/16835287094409.jpg",
                        "talla": "S",
                        "color": "Rojo"
                    },
                    {
                        "id": "15",
                        "categoria": "Accesorios",
                        "nombre": "Sombrero de ala ancha",
                        "empresa": "Estilo Vintage",
                        "descripcion_corta": "Sombrero de ala ancha para el verano",
                        "descripcion_larga": "Sombrero de ala ancha con estilo vintage perfecto para protegerse del sol en el verano. Fabricado con materiales duraderos. Disponible en varios colores. ¡Añade un toque retro a tu outfit veraniego!",
                        "precio": 34.99,
                        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXX6OHgOSQ476Wybi8Tfm4SKW_p43ORLTpmw&usqp=CAU",
                        "color": "Beige"
                    },
                    {
                        "id": "16",
                        "categoria": "Ropa",
                        "nombre": "Sudadera con capucha",
                        "empresa": "Estilo Deportivo",
                        "descripcion_corta": "Sudadera cómoda para actividades deportivas",
                        "descripcion_larga": "Sudadera con capucha y diseño deportivo. Ideal para actividades al aire libre y deportes. Confeccionada con materiales suaves y transpirables. Disponible en talla L y en varios colores. ¡Eleva tu comodidad durante tus entrenamientos con esta sudadera!",
                        "precio": 54.99,
                        "imagen": "https://hmecuador.vtexassets.com/arquivos/ids/573627-340-520?v=638105037902200000&width=340&height=520&aspect=true",
                        "talla": "L",
                        "color": "Gris"
                    },
                    {
                        "id": "17",
                        "categoria": "Zapatos",
                        "nombre": "Botines de tacón",
                        "empresa": "Calzado Chic",
                        "descripcion_corta": "Botines elegantes con tacón",
                        "descripcion_larga": "Botines de tacón alto con diseño elegante. Perfectos para ocasiones formales y salidas nocturnas. Disponibles en talla 6 y en varios colores. ¡Añade un toque de sofisticación a tu calzado con estos botines chic!",
                        "precio": 89.99,
                        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM6dggWm1vJBtb9TVv4y-lppYnM_tMv3kd67LZxsPH6k2ajMDfTR_QYFVknihRz4OlGRo&usqp=CAU",
                        "talla": "6",
                        "color": "Negro"
                    },
                    {
                        "id": "18",
                        "categoria": "Accesorios",
                        "nombre": "Bufanda de lana",
                        "empresa": "Estilo Invernal",
                        "descripcion_corta": "Bufanda suave y cálida",
                        "descripcion_larga": "Bufanda de lana suave y cálida para los días fríos de invierno. Diseño clásico y versátil. Disponible en varios colores. ¡Mantén tu cuello abrigado con esta encantadora bufanda invernal!",
                        "precio": 29.99,
                        "imagen": "https://static.wixstatic.com/media/d3ae6d_674f0bc7b82640138ba4f5909894a049~mv2.jpg/v1/fill/w_480,h_480,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/d3ae6d_674f0bc7b82640138ba4f5909894a049~mv2.jpg",
                        "color": "Morado"
                    },
                    {
                        "id": "19",
                        "categoria": "Ropa",
                        "nombre": "Falda plisada",
                        "empresa": "Estilo Femenino",
                        "descripcion_corta": "Falda plisada para un look femenino",
                        "descripcion_larga": "Falda plisada confeccionada en tejido ligero y cómodo. Ideal para un look femenino y elegante. Disponible en talla M y en varios colores. ¡Realza tu estilo con esta encantadora falda plisada!",
                        "precio": 39.99,
                        "imagen": "https://hmecuador.vtexassets.com/arquivos/ids/955426/Falda-plisada---Negro---H-M-EC.jpg?v=638259686004400000",
                        "talla": "M",
                        "color": "Rosa"
                    },
                    {
                        "id": "20",
                        "categoria": "Zapatos",
                        "nombre": "Mocasines de cuero",
                        "empresa": "Calzado Clásico",
                        "descripcion_corta": "Mocasines clásicos de cuero",
                        "descripcion_larga": "Mocasines de cuero clásicos y elegantes. Ideales para un look casual y cómodo. Disponibles en varias tallas y colores. ¡Añade un toque de estilo atemporal a tus pies con estos mocasines de cuero!",
                        "precio": 64.99,
                        "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVn42GcBWeFEa_dr4_AGZhPnio2nLEqpUUwJ3LS5pj77JUT8SMCxvsIJ2BL3tYrc7EMxc&usqp=CAU",
                        "talla": "8",
                        "color": "Marrón"
                    },{
                    "id": "21",
                    "categoria": "Accesorios",
                    "nombre": "Anillo de plata",
                    "empresa": "Joyas Modernas",
                    "descripcion_corta": "Anillo elegante de plata",
                    "descripcion_larga": "Anillo de plata con diseño moderno y elegante. Ideal para complementar cualquier look. Hecho con plata esterlina de alta calidad. ¡Añade un toque de brillo a tus manos con este hermoso anillo!",
                    "precio": 49.99,
                    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQCfhNeSxLqjRFa1o0wHHkVoxQvTSQ5kqmkWQPU2Ja60_DHG4Pv6v-kswp4-kzhXA_phik&usqp=CAU",
                    "color": "Plateado"
                },
                {
                    "id": "22",
                    "categoria": "Ropa",
                    "nombre": "Blusa de encaje",
                    "empresa": "Estilo Romántico",
                    "descripcion_corta": "Blusa delicada de encaje",
                    "descripcion_larga": "Blusa de encaje con diseño romántico y delicado. Perfecta para ocasiones especiales y salidas elegantes. Disponible en talla S y en varios colores. ¡Resalta tu feminidad con esta encantadora blusa!",
                    "precio": 39.99,
                    "imagen": "https://i5.walmartimages.com.mx/mg/gm/3pp/asr/ef3014dc-665b-4a41-b532-d12bee3ea1fd.228c3aa3f179c07434406c47808e17b0.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFFR",
                    "talla": "S",
                    "color": "Blanco"
                },
                {
                    "id": "23",
                    "categoria": "Zapatos",
                    "nombre": "Zapatillas de ballet",
                    "empresa": "Calzado Clásico",
                    "descripcion_corta": "Zapatillas de ballet elegantes",
                    "descripcion_larga": "Zapatillas de ballet con diseño clásico y elegante. Ideales para eventos formales y ocasiones especiales. Disponibles en talla 7 y en varios colores. ¡Añade un toque de gracia a tus pies con estas zapatillas!",
                    "precio": 59.99,
                    "imagen": "https://m.media-amazon.com/images/I/61Bj8LvpsSL.jpg",
                    "talla": "7",
                    "color": "Dorado"
                },
                {
                    "id": "24",
                    "categoria": "Ropa",
                    "nombre": "Jeans rasgados",
                    "empresa": "Estilo Urbano",
                    "descripcion_corta": "Jeans modernos con roturas",
                    "descripcion_larga": "Jeans modernos con efecto desgastado y roturas. Perfectos para un look urbano y casual. Confeccionados con denim de alta calidad. Disponibles en talla M y en varios tonos de azul. ¡Expresa tu estilo urbano con estos jeans llamativos!",
                    "precio": 69.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61PeSAgJY2L._AC_UY1000_.jpg",
                    "talla": "M",
                    "color": "Azul"
                },
                {
                    "id": "25",
                    "categoria": "Accesorios",
                    "nombre": "Cinturón de cuero",
                    "empresa": "Estilo Clásico",
                    "descripcion_corta": "Cinturón de cuero genuino",
                    "descripcion_larga": "Cinturón de cuero genuino con hebilla clásica. Añade un toque de elegancia a tus conjuntos. Disponible en varias tallas y colores. ¡Define tu estilo con este versátil cinturón!",
                    "precio": 34.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61RXmESqVpL._AC_UF1000,1000_QL80_.jpg",
                    "color": "Marrón"
                },
                {
                    "id": "26",
                    "categoria": "Ropa",
                    "nombre": "Vestido de fiesta",
                    "empresa": "Moda Glamurosa",
                    "descripcion_corta": "Vestido de fiesta con lentejuelas",
                    "descripcion_larga": "Vestido de fiesta con lentejuelas brillantes. Perfecto para eventos glamurosos y noches especiales. Disponible en talla L y en varios colores. ¡Brilla con este deslumbrante vestido de fiesta!",
                    "precio": 99.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51WubpvGI8L._AC_UY1000_.jpg",
                    "talla": "L",
                    "color": "Negro"
                },
                {
                    "id": "27",
                    "categoria": "Zapatos",
                    "nombre": "Botas de gamuza",
                    "empresa": "Calzado Sofisticado",
                    "descripcion_corta": "Botas elegantes de gamuza",
                    "descripcion_larga": "Botas de gamuza con diseño elegante y tacón alto. Perfectas para un look sofisticado. Disponibles en talla 8 y en varios colores. ¡Completa tu atuendo con estas botas de gamuza irresistibles!",
                    "precio": 79.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61FRQoLy39L._AC_UY1000_.jpg",
                    "talla": "8",
                    "color": "Gris"
                },
                {
                    "id": "28",
                    "categoria": "Accesorios",
                    "nombre": "Brazalete de cuero",
                    "empresa": "Estilo Rebelde",
                    "descripcion_corta": "Brazalete de cuero con tachuelas",
                    "descripcion_larga": "Brazalete de cuero con tachuelas para un toque rebelde. Ideal para complementar looks informales y audaces. Disponible en varios colores. ¡Añade un elemento de rebeldía a tu estilo con este brazalete!",
                    "precio": 24.99,
                    "imagen": "https://m.media-amazon.com/images/I/71UfZISxIHL._AC_UY580_.jpg",
                    "color": "Negro"
                },
                {
                    "id": "29",
                    "categoria": "Ropa",
                    "nombre": "Camiseta estampada",
                    "empresa": "Estilo Casual",
                    "descripcion_corta": "Camiseta con estampado gráfico",
                    "descripcion_larga": "Camiseta de manga corta con estampado gráfico moderno y divertido. Perfecta para un look casual y relajado. Disponible en talla XL y en varios diseños. ¡Expresa tu personalidad con esta camiseta estampada!",
                    "precio": 19.99,
                    "imagen": "https://bit.ly/3NA1ZJR",
                    "talla": "XL",
                    "color": "Multicolor"
                },
                {
                    "id": "30",
                    "categoria": "Zapatos",
                    "nombre": "Alpargatas de esparto",
                    "empresa": "Calzado Veraniego",
                    "descripcion_corta": "Alpargatas cómodas para el verano",
                    "descripcion_larga": "Alpargatas con suela de esparto ideales para los días soleados de verano. Diseño ligero y transpirable. Disponibles en talla 7 y en varios colores. ¡Camina con estilo y comodidad durante la temporada estival!",
                    "precio": 29.99,
                    "imagen": "https://m.media-amazon.com/images/I/61QOTJACY3L._AC_SY395_.jpg",
                    "talla": "7",
                    "color": "Beige"
                },{
                    "id": "31",
                    "categoria": "Ropa",
                    "nombre": "Vestido de lino",
                    "empresa": "Estilo Natural",
                    "descripcion_corta": "Vestido ligero de lino",
                    "descripcion_larga": "Vestido de lino ligero y fresco. Perfecto para días cálidos y eventos informales. Disponible en talla M y en varios tonos naturales. ¡Añade un toque natural y elegante a tu guardarropa con este vestido de lino!",
                    "precio": 49.99,
                    "imagen": "https://m.media-amazon.com/images/I/71ZbMCPmpuL._AC_UY1000_.jpg",
                    "talla": "M",
                    "color": "Beige"
                },
                {
                    "id": "32",
                    "categoria": "Accesorios",
                    "nombre": "Pañuelo de seda",
                    "empresa": "Estilo Chic",
                    "descripcion_corta": "Pañuelo de seda suave",
                    "descripcion_larga": "Pañuelo de seda suave y elegante. Ideal para complementar tus outfits con un toque chic. Disponible en varios estampados y colores. ¡Eleva tu estilo con este accesorio de seda!",
                    "precio": 39.99,
                    "imagen": "https://m.media-amazon.com/images/I/61ikDSrT7FL._AC_UY580_.jpg",
                    "color": "Estampado floral"
                },
                {
                    "id": "33",
                    "categoria": "Ropa",
                    "nombre": "Shorts de playa",
                    "empresa": "Moda Playera",
                    "descripcion_corta": "Shorts cómodos para la playa",
                    "descripcion_larga": "Shorts de playa cómodos y ligeros. Perfectos para disfrutar del sol y la arena. Disponibles en talla L y en varios colores veraniegos. ¡Prepárate para la diversión bajo el sol con estos shorts playeros!",
                    "precio": 24.99,
                    "imagen": "https://m.media-amazon.com/images/I/415PABP3MbL._AC_SY580_.jpg",
                    "talla": "L",
                    "color": "Azul turquesa"
                },
                {
                    "id": "34",
                    "categoria": "Zapatos",
                    "nombre": "Sneakers retro",
                    "empresa": "Calzado Vintage",
                    "descripcion_corta": "Sneakers con estilo retro",
                    "descripcion_larga": "Sneakers con diseño retro y suela gruesa. Perfectos para un look urbano y casual. Disponibles en talla 9 y en varios colores. ¡Añade un toque vintage a tu calzado con estas sneakers!",
                    "precio": 54.99,
                    "imagen": "https://m.media-amazon.com/images/I/71BB+L+fJ+L._AC_UY780_.jpg",
                    "talla": "9",
                    "color": "Blanco"
                },
                {
                    "id": "35",
                    "categoria": "Accesorios",
                    "nombre": "Cartera de cuero",
                    "empresa": "Estilo Elegante",
                    "descripcion_corta": "Cartera de cuero con compartimentos",
                    "descripcion_larga": "Cartera de cuero elegante con múltiples compartimentos. Ideal para organizar tus tarjetas y billetes con estilo. Disponible en varios colores clásicos. ¡Completa tu look con esta cartera funcional y sofisticada!",
                    "precio": 69.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71UA+7SvKwL._AC_UY1000_.jpg",
                    "color": "Negro"
                },
                {
                    "id": "36",
                    "categoria": "Ropa",
                    "nombre": "Polo de algodón",
                    "empresa": "Estilo Casual",
                    "descripcion_corta": "Polo clásico de algodón",
                    "descripcion_larga": "Polo de algodón clásico y versátil. Perfecto para un look casual y cómodo. Disponible en talla XL y en varios colores. ¡Completa tu colección de polos con esta prenda imprescindible!",
                    "precio": 29.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/513DYo8lyPL._AC_UF894,1000_QL80_.jpg",
                    "talla": "XL",
                    "color": "Verde oliva"
                },
                {
                    "id": "37",
                    "categoria": "Zapatos",
                    "nombre": "Mules de terciopelo",
                    "empresa": "Calzado Glamuroso",
                    "descripcion_corta": "Mules elegantes de terciopelo",
                    "descripcion_larga": "Mules de terciopelo con diseño elegante y tacón bajo. Ideales para eventos formales y salidas nocturnas. Disponibles en talla 6 y en varios colores. ¡Añade un toque de glamour a tus pies con estos mules!",
                    "precio": 74.99,
                    "imagen": "https://m.media-amazon.com/images/I/51h6ghqf2xL._AC_UY1000_.jpg",
                    "talla": "6",
                    "color": "Borgoña"
                },
                {
                    "id": "38",
                    "categoria": "Accesorios",
                    "nombre": "Gorra ajustable",
                    "empresa": "Estilo Deportivo",
                    "descripcion_corta": "Gorra deportiva ajustable",
                    "descripcion_larga": "Gorra deportiva con diseño ajustable para un ajuste perfecto. Ideal para actividades al aire libre y deportes. Disponible en varios colores y estilos. ¡Protege tu rostro del sol con estilo!",
                    "precio": 19.99,
                    "imagen": "https://http2.mlstatic.com/D_NQ_NP_987299-MLA48023758372_102021-O.webp",
                    "color": "Rojo"
                },
                {
                    "id": "39",
                    "categoria": "Ropa",
                    "nombre": "Jersey de punto",
                    "empresa": "Estilo Cálido",
                    "descripcion_corta": "Jersey de punto para el invierno",
                    "descripcion_larga": "Jersey de punto suave y cálido para los días fríos de invierno. Diseño clásico y versátil. Disponible en talla M y en varios colores. ¡Mantén el calor con este acogedor jersey de punto!",
                    "precio": 44.99,
                    "imagen": "https://m.media-amazon.com/images/I/51ve5WxBsGL._AC_UF894,1000_QL80_.jpg",
                    "talla": "M",
                    "color": "Gris oscuro"
                },
                {
                    "id": "40",
                    "categoria": "Zapatos",
                    "nombre": "Mocasines de cuero",
                    "empresa": "Calzado Clásico",
                    "descripcion_corta": "Mocasines clásicos de cuero",
                    "descripcion_larga": "Mocasines de cuero clásicos y elegantes. Ideales para un look casual y cómodo. Disponibles en varias tallas y colores. ¡Añade un toque de estilo atemporal a tus pies con estos mocasines de cuero!",
                    "precio": 64.99,
                    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRflLXhxf7NPKjEa6t0TwU65z1AViz4caRDfc3sP2AbdQOGEK6_fYt6H3ShN9Rdi8D7Ecw&usqp=CAU",
                    "talla": "8",
                    "color": "Marrón"
                },
                {
                    "id": "41",
                    "categoria": "Accesorios",
                    "nombre": "Reloj de pulsera",
                    "empresa": "Estilo Moderno",
                    "descripcion_corta": "Reloj de pulsera elegante",
                    "descripcion_larga": "Reloj de pulsera elegante con diseño moderno. Perfecto para complementar tus looks diarios. Carátula luminiscente y correa ajustable. ¡Mantén el tiempo con estilo con este elegante reloj de pulsera!",
                    "precio": 89.99,
                    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXcFqYA_XGRNBNlY2axeYIY8FhC22YIYcms3xPkFrARCmCHhe2x2Uzue1kmSXGNf248_0&usqp=CAU",
                    "color": "Negro"
                },
                {
                    "id": "42",
                    "categoria": "Ropa",
                    "nombre": "Blazer de lino",
                    "empresa": "Estilo Casual",
                    "descripcion_corta": "Blazer ligero de lino",
                    "descripcion_larga": "Blazer de lino ligero y versátil. Ideal para un look casual y elegante. Botones frontales y bolsillos funcionales. Disponible en talla L y en varios colores. ¡Añade un toque de sofisticación a tu vestuario con este blazer de lino!",
                    "precio": 79.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/51q-1dJ+xOL._AC_SL1020_.jpg",
                    "talla": "L",
                    "color": "Gris claro"
                },
                {
                    "id": "43",
                    "categoria": "Zapatos",
                    "nombre": "Sandalias de tacón",
                    "empresa": "Calzado Chic",
                    "descripcion_corta": "Sandalias elegantes con tacón",
                    "descripcion_larga": "Sandalias de tacón alto con diseño elegante. Perfectas para eventos formales y salidas nocturnas. Disponibles en talla 7 y en varios colores. ¡Completa tu look con estas sandalias de tacón chic!",
                    "precio": 69.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61c6BIcxAvL._AC_UY1000_.jpg",
                    "talla": "7",
                    "color": "Dorado"
                },
                {
                    "id": "44",
                    "categoria": "Ropa",
                    "nombre": "Vestido de verano",
                    "empresa": "Moda Estival",
                    "descripcion_corta": "Vestido ligero para el verano",
                    "descripcion_larga": "Vestido de verano ligero y fresco. Ideal para días cálidos y eventos casuales. Disponible en talla M y en varios colores. ¡Disfruta del verano con este encantador vestido estival!",
                    "precio": 59.99,
                    "imagen": "https://m.media-amazon.com/images/I/71DTtxpX6oL._AC_UY1000_.jpg",
                    "talla": "M",
                    "color": "Amarillo"
                },
                {
                    "id": "45",
                    "categoria": "Accesorios",
                    "nombre": "Pendientes de aro",
                    "empresa": "Joyas Trendy",
                    "descripcion_corta": "Pendientes modernos de aro",
                    "descripcion_larga": "Pendientes de aro con diseño moderno y llamativo. Perfectos para destacar tu estilo. Hechos con materiales de calidad. ¡Completa tu look con estos elegantes pendientes de aro!",
                    "precio": 29.99,
                    "imagen": "https://images-eu.ssl-images-amazon.com/images/I/61lSssuiLGL._AC_UL600_SR600,600_.jpg",
                    "color": "Plateado"
                },
                {
                    "id": "46",
                    "categoria": "Ropa",
                    "nombre": "Camisa a rayas",
                    "empresa": "Estilo Clásico",
                    "descripcion_corta": "Camisa clásica a rayas",
                    "descripcion_larga": "Camisa a rayas clásica y versátil. Ideal para ocasiones formales y looks de oficina. Botones frontales y corte cómodo. Disponible en talla XL y en varios colores. ¡Añade un toque elegante a tu vestuario con esta camisa a rayas!",
                    "precio": 49.99,
                    "imagen": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSi5dN8THppyvm_T13jRMBMVwfuuF58fJd9_w&usqp=CAU",
                    "talla": "XL",
                    "color": "Azul marino"
                },
                {
                    "id": "47",
                    "categoria": "Zapatos",
                    "nombre": "Bailarinas de cuero",
                    "empresa": "Calzado Femenino",
                    "descripcion_corta": "Bailarinas cómodas de cuero",
                    "descripcion_larga": "Bailarinas de cuero suave y cómodo. Ideales para un look femenino y casual. Disponibles en talla 6 y en varios colores. ¡Camina con comodidad y estilo con estas bailarinas de cuero!",
                    "precio": 39.99,
                    "imagen": "https://m.media-amazon.com/images/I/61+6oKNNl1L._AC_UF894,1000_QL80_.jpg",
                    "talla": "6",
                    "color": "Rosa"
                },
                {
                    "id": "48",
                    "categoria": "Accesorios",
                    "nombre": "Sombrero de paja",
                    "empresa": "Estilo Veraniego",
                    "descripcion_corta": "Sombrero de paja para el verano",
                    "descripcion_larga": "Sombrero de paja con diseño veraniego. Perfecto para protegerte del sol con estilo. Disponible en varios colores. ¡Añade un toque playero a tu outfit con este encantador sombrero de paja!",
                    "precio": 19.99,
                    "imagen": "https://m.media-amazon.com/images/I/71VPHF7NVdL._AC_UY1000_.jpg",
                    "color": "Natural"
                },
                {
                    "id": "49",
                    "categoria": "Ropa",
                    "nombre": "Chaleco acolchado",
                    "empresa": "Estilo Invernal",
                    "descripcion_corta": "Chaleco acolchado para el invierno",
                    "descripcion_larga": "Chaleco acolchado cálido y confortable para los días fríos de invierno. Cierre con cremallera y bolsillos funcionales. Disponible en talla L y en varios colores. ¡Mantén el calor con estilo con este chaleco acolchado!",
                    "precio": 54.99,
                    "imagen": "https://m.media-amazon.com/images/I/51giM6PgBaL._AC_UY1000_.jpg",
                    "talla": "L",
                    "color": "Verde oliva"
                },
                {
                    "id": "50",
                    "categoria": "Zapatos",
                    "nombre": "Botas altas",
                    "empresa": "Calzado Elegante",
                    "descripcion_corta": "Botas altas de piel",
                    "descripcion_larga": "Botas altas de piel con tacón alto. Perfectas para ocasiones elegantes y looks sofisticados. Disponibles en talla 8 y en varios colores. ¡Completa tu outfit con estas impresionantes botas altas!",
                    "precio": 89.99,
                    "imagen": "https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/61YmVqxhBBL._AC_UY1000_.jpg",
                    "talla": "8",
                    "color": "Negro"
                }
                ]
            );
        }, 2000);
    }, []);

    return productos;
}